import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { corsHeaders } from "../_shared/cors.ts";
import { getAuthUser } from "../_shared/auth.ts";

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const user = await getAuthUser(req);
    if (!user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { documentId, templateId, recordType, recordId } = await req.json();

    const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Update status to processing
    await supabase.from("documents").update({ generation_status: "processing" }).eq("id", documentId);

    // 1. Fetch template
    const { data: template, error: templateErr } = await supabase
      .from("document_templates")
      .select("*")
      .eq("id", templateId)
      .single();

    if (templateErr || !template) {
      await supabase
        .from("documents")
        .update({ generation_status: "failed", generation_error: "Template not found" })
        .eq("id", documentId);
      return new Response(JSON.stringify({ error: "Template not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // 2. Fetch record data
    const tableMap: Record<string, string> = {
      opportunity: "opportunities",
      project: "projects",
      job: "jobs",
      disposition: "dispositions",
      matter: "matters",
      rch_contract: "rch_contracts",
    };
    const tableName = tableMap[recordType];
    let recordData: Record<string, unknown> = {};

    if (tableName) {
      const { data: record } = await supabase.from(tableName).select("*").eq("id", recordId).single();
      recordData = (record as Record<string, unknown>) ?? {};
    }

    // Also fetch entity info
    const entityId = recordData.entity_id as string | undefined;
    if (entityId) {
      const { data: entity } = await supabase.from("entities").select("*").eq("id", entityId).single();
      if (entity) {
        recordData.entity = entity;
      }
    }

    // Add computed variables
    recordData._today = new Date().toISOString().split("T")[0];
    recordData._year = new Date().getFullYear().toString();
    recordData._generated_at = new Date().toISOString();

    // 3. Substitute variables in template HTML
    let html = template.template_html ?? template.template ?? "";

    // Replace {{variable}} patterns
    html = html.replace(/\{\{(\w+(?:\.\w+)*)\}\}/g, (_match: string, path: string) => {
      const parts = path.split(".");
      let value: unknown = recordData;
      for (const part of parts) {
        if (value && typeof value === "object") {
          value = (value as Record<string, unknown>)[part];
        } else {
          value = undefined;
          break;
        }
      }
      if (value === null || value === undefined) return "";
      if (typeof value === "number") {
        // Format currency-like numbers
        return value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
      }
      return String(value);
    });

    // 4. Generate PDF using simple HTML-to-PDF approach
    // Wrap in a basic HTML document
    const fullHtml = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Arial, sans-serif; font-size: 12px; line-height: 1.6; margin: 40px; }
    h1 { font-size: 24px; margin-bottom: 16px; }
    h2 { font-size: 18px; margin-bottom: 12px; }
    h3 { font-size: 14px; margin-bottom: 8px; }
    table { border-collapse: collapse; width: 100%; margin: 12px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background: #f5f5f5; font-weight: bold; }
    .header { border-bottom: 2px solid #1B3022; padding-bottom: 12px; margin-bottom: 24px; }
    .footer { border-top: 1px solid #ddd; padding-top: 12px; margin-top: 24px; font-size: 10px; color: #666; }
  </style>
</head>
<body>
${html}
<div class="footer">Generated by Tekton on ${new Date().toLocaleDateString()}</div>
</body>
</html>`;

    // Upload HTML as the generated document (PDF generation can be enhanced later)
    const fileName = `generated/${documentId}.html`;
    const { error: uploadErr } = await supabase.storage
      .from("documents")
      .upload(fileName, new Blob([fullHtml], { type: "text/html" }), {
        contentType: "text/html",
        upsert: true,
      });

    if (uploadErr) {
      await supabase
        .from("documents")
        .update({
          generation_status: "failed",
          generation_error: `Upload failed: ${uploadErr.message}`,
        })
        .eq("id", documentId);

      return new Response(JSON.stringify({ error: uploadErr.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Get public URL
    const { data: urlData } = supabase.storage.from("documents").getPublicUrl(fileName);

    // 5. Update document record
    await supabase
      .from("documents")
      .update({
        generation_status: "completed",
        generation_error: null,
        status: "active",
        storage_path: fileName,
        file_url: urlData?.publicUrl ?? null,
        file_size: new Blob([fullHtml]).size,
      })
      .eq("id", documentId);

    return new Response(JSON.stringify({ success: true, documentId, url: urlData?.publicUrl }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: (error as Error).message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
