import { useCallback, useEffect, useState } from "react";
import { SaveIndicator } from "@/components/shared/SaveIndicator";
import { type SaveStatus, useAutoSave } from "@/hooks/useAutoSave";
import { cn } from "@/lib/utils";

interface AutoSaveFieldProps {
  label: string;
  value: string | number | null | undefined;
  onSave: (value: string) => Promise<void>;
  type?: "text" | "number" | "email" | "tel" | "url" | "date" | "textarea";
  placeholder?: string;
  className?: string;
  disabled?: boolean;
  rows?: number;
  required?: boolean;
  autoValue?: string | number | null;
}

function computeFieldState(
  value: string,
  required?: boolean,
  autoValue?: string | number | null,
): { fieldState: string; isOverridden: boolean } {
  const isEmpty = value.trim() === "";
  const hasAutoValue = autoValue != null;
  const isOverridden = hasAutoValue && !isEmpty && value !== String(autoValue);
  const isAutoGenerated = hasAutoValue && !isOverridden && !isEmpty;
  const isRequiredEmpty = required && isEmpty && !hasAutoValue;

  const fieldState = isRequiredEmpty
    ? "field-required-empty"
    : isAutoGenerated
      ? "field-auto"
      : isOverridden
        ? "field-override"
        : "";

  return { fieldState, isOverridden };
}

export function AutoSaveField({
  label,
  value,
  onSave,
  type = "text",
  placeholder,
  className,
  disabled,
  rows = 3,
  required,
  autoValue,
}: AutoSaveFieldProps) {
  const [localValue, setLocalValue] = useState(String(value ?? ""));

  useEffect(() => {
    setLocalValue(String(value ?? ""));
  }, [value]);

  const saveFn = useCallback(
    async (v: string) => {
      if (v === String(value ?? "")) return;
      await onSave(v);
    },
    [onSave, value],
  );

  const { status } = useAutoSave(localValue, saveFn);

  const { fieldState, isOverridden } = computeFieldState(localValue, required, autoValue);

  const handleRevert = () => {
    if (autoValue != null) {
      const reverted = String(autoValue);
      setLocalValue(reverted);
      onSave(reverted);
    }
  };

  const inputClasses = cn(
    "w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground outline-none transition-colors",
    "focus:border-primary focus:ring-1 focus:ring-primary",
    "disabled:cursor-not-allowed disabled:opacity-50",
    className,
  );

  return (
    <div className={cn("space-y-1.5", fieldState)}>
      <div className="flex items-center justify-between">
        <label className="text-sm font-medium text-foreground">{label}</label>
        <SaveIndicator status={status} />
      </div>
      <div className="relative">
        {type === "textarea" ? (
          <textarea
            value={localValue}
            onChange={(e) => setLocalValue(e.target.value)}
            placeholder={placeholder ?? (required ? "Required" : undefined)}
            disabled={disabled}
            rows={rows}
            className={cn(inputClasses, "resize-y")}
          />
        ) : (
          <input
            type={type}
            value={localValue}
            onChange={(e) => setLocalValue(e.target.value)}
            placeholder={placeholder ?? (required ? "Required" : undefined)}
            disabled={disabled}
            className={inputClasses}
          />
        )}
        {isOverridden && (
          <button
            type="button"
            onClick={handleRevert}
            className="absolute right-2.5 top-1/2 -translate-y-1/2 text-sm font-bold text-foreground opacity-70 hover:opacity-100"
            title="Revert to auto-calculated value"
          >
            {"\u2715"}
          </button>
        )}
      </div>
    </div>
  );
}

// Simpler select field with auto-save
interface AutoSaveSelectProps {
  label: string;
  value: string | null | undefined;
  onSave: (value: string) => Promise<void>;
  options: readonly string[] | { label: string; value: string }[];
  placeholder?: string;
  className?: string;
  disabled?: boolean;
  required?: boolean;
  autoValue?: string | null;
}

export function AutoSaveSelect({
  label,
  value,
  onSave,
  options,
  placeholder,
  className,
  disabled,
  required,
  autoValue,
}: AutoSaveSelectProps) {
  const [localValue, setLocalValue] = useState(value ?? "");
  const [status, setStatus] = useState<SaveStatus>("idle");

  useEffect(() => {
    setLocalValue(value ?? "");
  }, [value]);

  const { fieldState, isOverridden } = computeFieldState(localValue, required, autoValue);

  const handleChange = async (newValue: string) => {
    setLocalValue(newValue);
    if (newValue === (value ?? "")) return;
    setStatus("saving");
    try {
      await onSave(newValue);
      setStatus("saved");
      setTimeout(() => setStatus("idle"), 2000);
    } catch {
      setStatus("error");
    }
  };

  const handleRevert = () => {
    if (autoValue != null) {
      handleChange(autoValue);
    }
  };

  return (
    <div className={cn("space-y-1.5", fieldState)}>
      <div className="flex items-center justify-between">
        <label className="text-sm font-medium text-foreground">{label}</label>
        <SaveIndicator status={status} />
      </div>
      <div className="relative">
        <select
          value={localValue}
          onChange={(e) => handleChange(e.target.value)}
          disabled={disabled}
          className={cn(
            "w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground outline-none transition-colors",
            "focus:border-primary focus:ring-1 focus:ring-primary",
            "disabled:cursor-not-allowed disabled:opacity-50",
            className,
          )}
        >
          {placeholder && (
            <option value="" disabled>
              {placeholder}
            </option>
          )}
          {options.map((opt) => {
            const val = typeof opt === "string" ? opt : opt.value;
            const lbl = typeof opt === "string" ? opt : opt.label;
            return (
              <option key={val} value={val}>
                {lbl}
              </option>
            );
          })}
        </select>
        {isOverridden && (
          <button
            type="button"
            onClick={handleRevert}
            className="absolute right-8 top-1/2 -translate-y-1/2 text-sm font-bold text-foreground opacity-70 hover:opacity-100"
            title="Revert to auto-calculated value"
          >
            {"\u2715"}
          </button>
        )}
      </div>
    </div>
  );
}
