import { useState } from "react";
import { cn } from "@/lib/utils";

interface FormFieldProps {
  label: string;
  name: string;
  value: string | number | null;
  onChange: (value: string) => void;
  required?: boolean;
  autoValue?: string | number | null;
  readOnly?: boolean;
  type?: string;
  placeholder?: string;
}

export function FormField({
  label,
  name,
  value,
  onChange,
  required,
  autoValue,
  readOnly,
  type = "text",
  placeholder,
}: FormFieldProps) {
  const [isOverridden, setIsOverridden] = useState(false);

  const isEmpty = value === null || value === undefined || String(value).trim() === "";
  const hasAutoValue = autoValue !== null && autoValue !== undefined;
  const isAutoGenerated = hasAutoValue && !isOverridden;
  const isManualOverride = hasAutoValue && isOverridden;
  const isRequiredEmpty = required && isEmpty && !hasAutoValue;

  const displayValue = isAutoGenerated ? String(autoValue) : (value ?? "");

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (hasAutoValue) setIsOverridden(true);
    onChange(e.target.value);
  };

  const handleRevert = () => {
    setIsOverridden(false);
    onChange(String(autoValue));
  };

  const fieldState = isRequiredEmpty
    ? "field-required-empty"
    : isAutoGenerated
      ? "field-auto"
      : isManualOverride
        ? "field-override"
        : "";

  return (
    <div className={cn("relative flex flex-col", fieldState)}>
      <label htmlFor={name} className="mb-1 flex items-center gap-1 text-xs font-medium text-muted-foreground">
        {required && <span className="font-bold text-destructive">*</span>}
        {label}
      </label>
      <input
        id={name}
        type={type}
        name={name}
        value={String(displayValue)}
        onChange={handleChange}
        readOnly={readOnly || isAutoGenerated}
        placeholder={placeholder || (required ? "Required" : "")}
        className={cn(
          "rounded-md border px-3 py-2 text-sm transition-all",
          "focus:outline-none focus:ring-2 focus:ring-ring/20 focus:border-ring",
        )}
      />
      {isManualOverride && (
        <button
          type="button"
          onClick={handleRevert}
          className="absolute bottom-2.5 right-2.5 text-sm font-bold text-foreground opacity-70 hover:opacity-100"
          title="Revert to auto-calculated value"
        >
          {"\u2715"}
        </button>
      )}
    </div>
  );
}
